config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :bookmarkers

  get 'friends_list', to: 'bookmarkers#friends_list'

  devise_for :users, controllers: { omniauth_callbacks: 'auth/callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmarker.rb
class Bookmarker < ApplicationRecord
  include PgSearch

  has_attached_file :snapshot, styles: { medium: '200x200>' }, default_url: '/images/missing.png'
  validates_attachment :snapshot, content_type: { content_type: %w[image/jpg image/jpeg image/png] }

  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true, uniqueness: true, length: { in: 3..50 }
  validates :url, format: { with: Regexp.new(URI.regexp(%w[http https])) }, presence: true

  default_scope { order(created_at: :desc) }

  scope :search_like, ->(term) { where('title ILIKE ? OR url ILIKE ?', "%#{term}%", "%#{term}%") }

  pg_search_scope :search_by_title_and_url, against: %i[title url],
                                            using: {
                                              tsearch: {
                                                prefix: true,
                                                any_word: true
                                              }
                                            }
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :bookmarkers

  devise :omniauthable, omniauth_providers: [:facebook]

  def self.create_from_omniauth(params)
    user = find_or_create_by(email: params.info.email, uid: params.uid)
    user.update(token: params.credentials.token,
                name: params.info.name,
                email: params.info.email,
                avatar: params.info.image)
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarkers_controller.rb
class BookmarkersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bookmarker, only: %i[show edit update destroy]

  def index
    @usr = params[:uid] ? User.find_by_uid(params[:uid]) : current_user

    @bookmarkers = @usr.bookmarkers
    @bookmarkers = if params[:term] && !params[:term].blank?
                     @bookmarkers.search_like(params[:term])
                   else
                     @bookmarkers
                   end

    @bookmarkers = @bookmarkers.order(:created_at).page(params[:page]).per(params[:limit])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    if current_user
      @bookmarker = Bookmarker.new
    else
      redirect_to root_path
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @bookmarker = Bookmarker.create(bookmarker_params)
    @bookmarker.user = current_user if current_user

    respond_to do |format|
      if @bookmarker.save
        webshot_upload_image
        format.html { redirect_to bookmarkers_url, notice: 'Bookmark was successfully created.' }
      else
        format.html
      end
      format.js
    end
  end

  def update
    respond_to do |format|
      if @bookmarker.update(bookmarker_params)
        format.html { redirect_to bookmarkers_url, notice: 'Bookmark was successfully updated.' }
      else
        format.html
      end
      format.js
    end
  end

  def edit
    redirect_to root_path unless @bookmarker.user.eql?(current_user)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    if @bookmarker.user.eql?(current_user)
      @bookmarker.destroy
      respond_to do |format|
        format.html { redirect_to bookmarkers_url, notice: 'Bookmark was successfully destroyed.' }
      end
    else
      redirect_to root_path
    end
  end

  def friends_list
    if current_user
      list = Facebook.friends_list(current_user.token)
      @friends = list.map { |f| User.find_by_uid(f["id"]) }
    end
  end

  private

  def webshot_upload_image
    ws = Webshot::Screenshot.instance
    ws.capture @bookmarker.url, 'tmp/webshot.png', width: 300, height: 300
    tmp_file = File.open('tmp/webshot.png', 'r')
    @bookmarker.snapshot = tmp_file
    tmp_file.close
    @bookmarker.save
  end

  def set_bookmarker
    @bookmarker = Bookmarker.find(params[:id])
    return if @bookmarker.present?
    flash[:alert] = 'Bookmark not found.'
    redirect_to root_path
  end

  def bookmarker_params
    params.require(:bookmarker).permit(:title, :url)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to bookmarkers_path(uid: current_user.uid)
    else
      render 'index'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarkers_helper.rb
module BookmarkersHelper
end

app/views/bookmarkers/_bookmarker.html.erb
<div class="col-md-3">
  <div class="card">
    <div class="side-crop">
      <%= link_to image_tag(bookmarker.snapshot.url, width: '300'), bookmarker.url %>
    </div>
    <div class="card-body">
      <% if bookmarker.user.eql?(current_user) %>
          <h6 class="card-title"><%= bookmarker.title %></h6>
          <p class="card-text">
            <%= link_to 'Edit', edit_bookmarker_path(bookmarker), remote: true, :class => 'btn btn-info btn-sm' %>
            <%= link_to 'Delete', bookmarker, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-info btn-sm ' %>
          </p>
      <% else %>
          <h6 class="card-title"><%= bookmarker.title %></h6>
      <% end %>
    </div>
  </div>
</div>

app/views/bookmarkers/_bookmarkers_cards.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row">
      <%= render @bookmarkers%>
      <% if @bookmarkers.blank? %>
          <div id="no-results"><h3> No results for you </h3></div>
      <% end %>
    </div>
  </div>
</div>

<%= paginate @bookmarkers, params: {uid: params[:uid]} %>

app/views/bookmarkers/_bookmarkes_cards.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row">
      <%= render @bookmarkers%>
      <% if @bookmarkers.blank? %>
          <div id="no-results"><h3> No results for you </h3></div>
      <% end %>
    </div>
  </div>
</div>

<%= paginate @bookmarkers, params: {uid: params[:uid]} %>

app/views/bookmarkers/_error.html.erb
<ul>
  <% @bookmarker.errors.full_messages.each do |message| %>
      <li><%= message %></li>
  <% end %>
</ul>

app/views/bookmarkers/_form.html.erb
<%= form_for @bookmarker, remote: true, :html => {:class => 'form-horizontal'} do |f| %>
    <div id="error_explanation">
    </div>
    <br>
    <fieldset>
      <div class="form-group">
        <%= f.label :title , class: 'col-md-4 control-label', for: 'textinput' %>
        <div><%= f.text_field :title, placeholder: 'title', class: 'form-control input-md' %></div>
      </div>
      <div class="form-group">
        <%= f.label :url, class: 'col-md-4 control-label', for: 'textarea'%><br>
        <div><%= f.text_area :url, class: 'form-control' %></div>
      </div>
      <div class="form-group">
        <label class="control-label" for="singlebutton"></label>
        <div>
          <div class="actions">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </fieldset>
<% end %>

app/views/bookmarkers/_navbar.html.erb
<section class="jumbotron">
  <div id="friends-button"><%= link_to 'Friends bookmarks', friends_list_url, :class => 'btn btn-success btn-lg' %></div>
  <div id="add-button">
    <%= link_to 'Add Bookmark',
                (new_bookmarker_path if current_user),
                class: 'btn btn-primary btn-lg',
                remote: true,
                'data-toggle' => "modal",
                'data-target' => '#modal-window' %>
  </div>
</section>

<%= form_tag(bookmarkers_path, method: :get, role: 'form') do %>
    <div class='row'>
      <div class="col-lg-6 offset-lg-3">
        <div class="input-group">
          <%= text_field_tag :term, params[:term], placeholder: 'Search for...', class: 'form-control' %>
          <%= hidden_field_tag :uid, params[:uid], class: 'form-control' %>
          <span class="input-group-btn">
            <%= submit_tag 'Search', class: 'btn btn-secondary' %>
          </span>
        </div>
      </div>
    </div>
<% end %>
</br>

app/views/bookmarkers/_new.html.erb
<div class="modal fade" id="modal-window" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Bookmark</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/bookmarkers/create.js.erb
<% if @bookmarker.errors.blank? %>
  $('#modal-window').modal('hide');
  location.reload();
<% else %>
  $("#error_explanation").html("<%= j render 'error' %>");
<% end %>

app/views/bookmarkers/edit.js.erb
$('<%= j render 'new' %>').on('hidden.bs.modal', function () {
    $(this).remove();
    $('.modal-backdrop').remove();
}).modal();

app/views/bookmarkers/friends_list.html.erb
<div class="container-fluid">
  <main role="main">
    <%= render 'home/user' %>

    <div class="friends-title"><h2>Friends bookmarks</h2></div>
    <div>
      <ul id="friends-list" class="list-group">
        <% if @friends.any? %>
            <div>
              <% @friends.each do |f| %>
                  <li class="list-group-item">
                    <%= image_tag f.avatar, class: 'rounded-circle'%>
                    <%= link_to f.name, bookmarkers_path(uid: f.uid) %>
                  </li>
                  </div>
              <% end %>
        <% end %>
      </ul>
    </div>
  </main>
</div>

app/views/bookmarkers/index.html.erb
<% if user_signed_in? %>
    <%= render 'home/user' %>
    <div class="container-fluid">

      <main role="main">

        <% if current_user.uid == params[:uid] %>
            <%= render 'navbar'  %>
        <% else %>
            <div class="friends-title"><h2><%= @usr.name %>'s  bookmarks</h2></div>
        <% end %>
        <div>
          <%= form_tag bookmarkers_path(uid: params[:uid]), method: :get, id: 'limit_form', remote: true do %>

              <div id="select-cards" class="select-tag">
                Show
                <%= select_tag :limit,
                               options_for_select([4, 8, 12, 16, 20], selected: params[:limit] || 8),
                               class: 'custom-select',
                               onchange: "$('#limit_form').submit();" %>
                items per page
              </div>

              <div id="bookmarkers_cards">
                <%= render 'bookmarkers_cards'%>
              </div>
          <% end %>
        </div>

      </main>
<% else %>
    <%= render 'home/login' %>
<% end %>
</div>

app/views/bookmarkers/index.js.erb
$("#bookmarkers_cards").html("<%= j render 'bookmarkers_cards' %>");

app/views/bookmarkers/new.js.erb
$('<%= j render 'new' %>').on('hidden.bs.modal', function () {
    $(this).remove();
    $('.modal-backdrop').remove();
}).modal();

app/views/bookmarkers/update.js.erb
<% if @bookmarker.errors.blank? %>
  $('#modal-window').modal('hide');
  location.reload();
<% else %>
  $("#error_explanation").html("<%= j render 'error' %>");
<% end %>

app/views/home/_login.html.erb
<body>
<div class="container">
  <div class="jumbotron mt-3 text-center">
    <h2>Bookmarks App</h2>
    <%= link_to 'Facebook login', user_facebook_omniauth_authorize_url, class: 'btn btn-lg btn-primary' %>
  </div>
</div>
</body>

app/views/home/_user.html.erb
<div>
  <div class="navbar navbar-dark bg-dark">
    <div class="container-fluid d-flex justify-content-between">
      <div class="navbar-brand">

        <%= image_tag current_user.avatar, class: 'rounded-circle', id: 'avatar' %>

        <div class="user_name">
          <%= current_user.name %>
        </div>
      </div>
      <div class="jumbotron-heading text-center"><h1><%= link_to 'Bookmarks', bookmarkers_url(uid: current_user.uid), id: 'main-title' %></h1></div>
      <div><%= link_to 'Logout', destroy_user_session_url, method: :delete, :class => 'btn btn-secondary' %></div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'login' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Bookmarks</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>

<body>
<%= yield %>
</body>
</html>